#+TITLE: drmrd's Org Init File
#+AUTHOR: drmrd
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args    :comments link :eval query :results output silent
#+STARTUP: indent
* Introduction
This file contains most of the settings and customizations pertaining
to org-mode contained in my Emacs configuration. It has only recently
been branched into its own file from [[file:~/.emacs.d/init.org][my main init file]], and so it is
nowhere near as organized as I'd like it to be. I also have a tendency
to tweak my org configuration constantly, probably at a frequency
second only to how often I tweak various LaTeX-related modes, and
sometimes the documentation included in this file gets a bit behind
its current state. All that to say, sorry for the mess, take what's
said in this file with a grain of salt, and use this config file (and,
really, all my config files) at your own risk!

It's also worth noting that I have to require Org before using
org-babel in my [[file:~/.emacs.d/.emacs][.emacs]] file to ensure that the most recent version of
Org is always loaded (instead of the built-in one). (Yes there are
probably other solutions, but they might involve modifying built-in
file names that I don't have write privileges for on campus PCs. This
is just a good fool-proof way to address the problem without too big a
cost to the structure of my config files.) Some org libraries must be
loaded prior to tangling [[file:~/.emacs.d/init.org][init.org]] (org-crypt, for instance), and so a
minimal configuration for these is provided in my [[file:~/.emacs.d/.emacs][.emacs]] file.
* General Settings & Keybindings                                :Keybindings:
** Navigation                                                   :Navigation:
#+SRC_NAME org-mode/general-settings/navigation
#+BEGIN_SRC emacs-lisp :tangle yes
  ; (when (boundp 'spacemacs-version) "yes")
  (setq org-special-ctrl-a/e t)
#+END_SRC

** Editing                                                         :Editing:

#+SRC_NAME org-mode/general-settings/editing
#+BEGIN_SRC emacs-lisp
  (setq org-M-RET-may-split-line '((headline) (item) (default . t)))

  (define-key org-mode-map (kbd "C-M-<enter>") 'org-insert-subheading)
  (define-key org-mode-map (kbd "C-M-S-<enter>") 'org-insert-todo-subheading)
#+END_SRC

** TODO Move other generic keybindings here
* Configure Default Directory, Agenda Directory, and Notes File
For now the org-agenda-files list simply contains ~/org, but it can
readily be modified to a list of subdirectories, files, etc. if
necessary.
#+BEGIN_SRC emacs-lisp
  (setq org-directory "~/org")
#+END_SRC
* Hyperlinks
** Custom Hyperlinks
#+SRCNAME org_custom_hyperlink_names
#+BEGIN_SRC emacs-lisp
  ;;; Create custom hyperlink prefixes for org-mode. For any prefix
  ;;; `foo' defined in this list, writing (in any org file)
  ;;;     [[foo:suffix][description]]
  ;;; will display a link in org with text `description' and pointing to
  ;;; the expansion of `foo' in this list, with the following
  ;;; replacement rules:
  ;;;
  ;;;     - If the expansion text is a string without any of the
  ;;;       items listed in the next three bullets as substrings, simply
  ;;;       insert the contatenation of this replacement string and
  ;;;       `suffix'.
  ;;;     - "%s" is replaced by `suffix'
  ;;;     - "%h" is replaced by `suffix' converted into a url-encoded
  ;;;            string using the `url-hexify-string' function
  ;;;     - "%(some-function)" is replaced by the output of
  ;;;            `some-function'. It is assumed that `some-function'
  ;;;            takes a single argument (which will be `suffix' here)
  ;;;            as input and outputs a string.
  ;;;     - The expansion of `foo' can also be a function (instead of a
  ;;;       string), which is assumed to be of the same form (in terms
  ;;;       of inputs and outputs) as `some-function' in the previous
  ;;;       bullet.
  ;;;
  ;;; See the description of this variable for more info.
  (setq org-link-abbrev-alist
        '(("google" . "http://www.google.com/search?q=")
          ("map"    . "http://maps.google.com/maps?q=%s")
          ("wiki"   . "https://en.wikipedia.org/wiki/%s")))
#+END_SRC
*** TODO Test these further and improve with %(some-function) calls
For instance, check to see if I need to change the "wiki" linkkey's
expansion to either %h or something like %(drmrd/spaces-to-underlines)
to ensure that Wikipedia links are working as expected.
* Task Management (TODO Keywords, Tags, etc.)
** Settings for TODOs
*** Set the TODO keywords
The globally-defined TODO keywords are stored in the
[[help:org-todo-keywords][=org-todo-keywords=]] variable. There is a
lot you can do with these, so see the documentation of this variable
for all the details. In summary, it is a list of "TODO entry keyword
sequences" which are themselves lists of the form

#+BEGIN_EXAMPLE
  (<sequence or type>
    "K1" [...] "Km"
    [optionally "|" "DK1" [...] "DKn"])
#+END_EXAMPLE

where the first element is =sequence= if the subsequent elements should
be interpreted as a sequence of "action steps" and =type= if the
subsequent elements should be interpreted as specifying different types
of TODO items. Additionally, if the first element is =sequence= then
 1. "K1",...,"K<m-1>" always represent states requiring action, as does
    "Km" if "|" appears in the list. Otherwise "Km" represents a (unique)
    DONE state in which no additional action is necessary.
 2. "DK1",...,"DKn" represent states in which no further action is
    necessary.

By default the value is =((sequence "TODO" "DONE"))=

#+SRC_NAME redef_org-todo-keywords
#+BEGIN_SRC emacs-lisp
  ; Courtesy of http://doc.norang.ca/org-mode.html#TasksAndStates
  (setq-default org-todo-keywords
        (quote ((sequence "TODO(t)" "|" "DONE(d)")
                (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)")
                (sequence "PHONE")
                (sequence "MEETING"))))

  (setq-default org-todo-keyword-faces
        (quote (("TODO" :foreground "red" :weight bold)
                ("NEXT" :foreground "blue" :weight bold)
                ("DONE" :foreground "forest green" :weight bold)
                ("WAITING" :foreground "orange" :weight bold)
                ("HOLD" :foreground "gray" :weight bold)
                ("CANCELLED" :foreground "gray" :weight bold)
                ("MEETING" :foreground "forest green" :weight bold)
                ("PHONE" :foreground "forest green" :weight bold))))

  ;(setq-default org-todo-keywords
  ;  '((sequence "TODO(t)" "MAYBE(m)" "STARTED(s)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)")))
#+END_SRC
*** Toggle timestamps and/or notes when TODOs are toggled between =TODO= and =DONE=
The behavior of the =org-todo= command, bound to C-c C-t by default,
is controlled in part by the [[help:org-log-done][=org-log-done=]] variable. If this is set
to =nil= then no timestamp or note is inserted when a task is marked
as =DONE= (this is the default behavior). If it is set to =time=, then
the timestamp from when the task was completed is inserted on the next
line (and removed if the task is marked as incomplete later). If set
to =note=, the timestamp is inserted and the user is prompted for
input to insert onto an additional line in the format specified by the
[[help:org-log-note-headings][org-log-note-headings]] variable.
#+BEGIN_SRC emacs-lisp
  (setq-default org-log-done 'time)
#+END_SRC
* Diary
While not technically an Org feature, I use the Emacs diary almost exclusively
with Org mode, so it makes some sense to configure it here.
#+SRC_NAME diary_settings
#+BEGIN_SRC emacs-lisp
  (setq diary-file (expand-file-name "~/org/diary"))
#+END_SRC
* Org Link                                              :Hyperlinks:org_link:
** Custom Hyperlinks
#+SRCNAME org_custom_hyperlink_names
#+BEGIN_SRC emacs-lisp
  ;;; Create custom hyperlink prefixes for org-mode. For any prefix
  ;;; `foo' defined in this list, writing (in any org file)
  ;;;     [[foo:suffix][description]]
  ;;; will display a link in org with text `description' and pointing to
  ;;; the expansion of `foo' in this list, with the following
  ;;; replacement rules:
  ;;;
  ;;;     - If the expansion text is a string without any of the
  ;;;       items listed in the next three bullets as substrings, simply
  ;;;       insert the contatenation of this replacement string and
  ;;;       `suffix'.
  ;;;     - "%s" is replaced by `suffix'
  ;;;     - "%h" is replaced by `suffix' converted into a url-encoded
  ;;;            string using the `url-hexify-string' function
  ;;;     - "%(some-function)" is replaced by the output of
  ;;;            `some-function'. It is assumed that `some-function'
  ;;;            takes a single argument (which will be `suffix' here)
  ;;;            as input and outputs a string.
  ;;;     - The expansion of `foo' can also be a function (instead of a
  ;;;       string), which is assumed to be of the same form (in terms
  ;;;       of inputs and outputs) as `some-function' in the previous
  ;;;       bullet.
  ;;;
  ;;; See the description of this variable for more info.
  (setq-default org-link-abbrev-alist
        '(("google" . "http://www.google.com/search?q=")
          ("map"    . "http://maps.google.com/maps?q=")
          ("wiki"   . "https://en.wikipedia.org/wiki/")
          ("github" . "https://github.com/")))
#+END_SRC
*** TODO Test these further and improve with %(some-function) calls
For instance, check to see if I need to change the "wiki" linkkey's
expansion to either %h or something like %(drmrd/spaces-to-underlines)
to ensure that Wikipedia links are working as expected.
** PDF Support                                            :PDFs:org_pdfview:
The following package allows links to lines in PDF files to be opened in
~pdf-view~ mode instead of an external viewer.

#+SRC_NAME org-pdfview_use-package
#+BEGIN_SRC emacs-lisp
  (use-package org-pdfview :ensure t)
#+END_SRC
* Org Agenda
** Set Agenda & Note Files
#+BEGIN_SRC emacs-lisp :tangle yes
  (require 'org-agenda)
  (setq org-agenda-files
        (mapcar 'drmrd/org-file-to-path
                '("calendar.org"
                  "habits.org"
                  "tasks.org"
                  "dissertating.org"
                  )))

  (setq org-agenda-include-diary      t
        org-agenda-timegrid-use-ampm  t
        org-agenda-span               'day
  )

  ;; ; The next setting and function are courtesy of:
  ;; ;     http://dept.stat.lsa.umich.edu/~jerrick/org_agenda_calendar.html
  ;; (add-hook 'org-finalize-agenda-hook
  ;;           (lambda ()
  ;;             (save-excursion
  ;;               ; TODO: Customize color-org-header so that it doesn't color everything in the line, effectively making habit graphs useless.
  ;;               (color-org-header "Habits:"     "gold")
  ;;               )))

  ;; (defun color-org-header (tag col)
  ;;   "Color agenda items with category TAG (including trailing
  ;; colon) with color COL."
  ;;   (interactive)
  ;;   ;(goto-char (point-min))
  ;;   ;(while (re-search-forward tag nil t)
  ;;   ;  (add-text-properties (match-beginning 0) (point-at-eol)
  ;;   ;                       `(face (:foreground ,col))))
  ;; )
#+END_SRC
** Connect to =appt=                          :appt:Reminders:Notifications:
Improve org-agenda-to-appt so that it reliably sends appointments to =appt=,
Emacs's built-in appointment reminder system and creates desktop notifications
with audio(!!!). This depends on a separate appt-notification.sh, which I've
added to this directory. To get the speech capabilities (hence, for
appt-notification.sh to run in its current state), you also need the packages
=espeak=, =mbrola=, and =mbrola-en1= installed, each of which is available
via =apt-get=.

This code is a modified form of that posted by user @scaramouche in [[http://emacs.stackexchange.com/a/5821/8643][this answer]]
to a question on Emacs.SE and @holocronweaver's comment in response.
#+BEGIN_SRC emacs-lisp :tangle no
  (require 'appt)
  (appt-activate t)

  (setq-default appt-message-warning-time 30) ; Show notification 5 minutes before event
  (setq-default appt-display-interval appt-message-warning-time) ; Disable multiple reminders
  (setq-default appt-display-mode-line nil)

  ; Use appointment data from org-mode
  (defun my-org-agenda-to-appt ()
    (interactive)
    (setq appt-time-msg-list nil)
    (org-agenda-to-appt))

  ; Update alarms when...
  ; (1) ... Starting Emacs
  (my-org-agenda-to-appt)

  ; (2) ... Everyday at 12:05am (useful in case you keep Emacs always on)
  (run-at-time "12:05am" (* 24 3600) 'my-org-agenda-to-appt)

  ; (3) ... When tasks.org is saved
  (add-hook 'after-save-hook
            '(lambda ()
               (catch 'found-buffer-name
                 (dolist (agenda-file-name org-agenda-files)
                   (if (string= (buffer-file-name) (expand-file-name agenda-file-name))
                       (progn (my-org-agenda-to-appt)
                              (throw 'found-buffer-name t)))))))

  ; (4) ... Quitting org-agenda
  (advice-add 'org-agenda-quit :after #'my-org-agenda-to-appt)

  ; Display appointments as a window manager notification
  (setq-default appt-disp-window-function 'my-appt-display)
  (setq-default appt-delete-window-function (lambda () t))

  (setq-default my-appt-notification-app (expand-file-name "~/.emacs.d/lib/appt-notification.sh"))

  (defun my-appt-display (min-to-app new-time msg)
    (if (atom min-to-app)
      (call-process my-appt-notification-app nil nil nil min-to-app msg)
    (dolist (i (number-sequence 0 (1- (length min-to-app))))
      (call-process my-appt-notification-app nil nil nil (nth i min-to-app) (nth i msg)))))
#+END_SRC
* Org Present
Present Org files as slideshows.
#+SRC_NAME org-present_use-package
#+BEGIN_SRC emacs-lisp :tangle no
; (unless (boundp 'spacemacs-version) "yes")
    (use-package org-present
      :config (add-hook 'org-present-mode-hook
                        (lambda ()
                          (org-present-big)
                          (org-display-inline-images)
                          (org-present-hide-cursor)
                          (org-present-read-only)))
              (add-hook 'org-present-mode-quit-hook
                        (lambda ()
                          (org-present-small)
                          (org-remove-inline-images)
                          (org-present-show-cursor)
                          (org-present-read-write))))
#+END_SRC
* Org Capture
Now we bind [[help:org-capture][org-capture]] mode globally to =C-c c=. This and the capture templates
that follow will allow us to automatically create TODOs, notes, etc., linked to
the current pointer location in another file, and store them in our default
notes file. (Of course, there are unlimited other possibilities here for
automating this further/creating additional templates that we could also setup,
but these should suffice for now.)  A task may be started with the "C-c C-c"
command in this mode, which will make org-capture start monitoring time spent on
the given task.

#+SRC_NAME keybinding_global_org-capture
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC
** Set Default Notes File
#+BEGIN_SRC emacs-lisp
  (setq-default org-default-notes-file "~/org/refile.org")
#+END_SRC
** Templates                                                     :Templates:
*** Overview
:PROPERTIES:
:VISIBILITY: folded
:END:
The syntax for capture templates is as follows (see [[help:org-capture-templates][the documentation]] for
details):

#+NAME org-capture-template-entry-format
#+BEGIN_EXAMPLE
  (keys description type target template property1 property2 ...)
#+END_EXAMPLE

Every item in the list is required with the exception of the trailing
properties. (This is, of course, not the case for template key prefix entries,
which require (and can only contain) the key and description entries.)
*** Configuration
#+SRC_NAME set_org-capture-templates
#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
        `(("a" "Got an Ansible-related defect? Shove that SOB in here!" entry
           (file+olp ,(drmrd/org-file-to-path "ansible.org") "PR Opportunities")
           "** %^{Short Summary}\n%^{Description (optional)}\n"
           :prepend t :immediate-finish nil :kill-buffer t)

          ("b" "Bits")
          ("be" "Dan's Roadside Emporium Ideas" entry
           (file ,(drmrd/org-file-to-path "refile.org"))
           ,(s-concat "* %^{Roadside Emporium Idea} %^g:DansRoadsideEmporium:Bits:\n"
                      "%^{Description (optional)}\n")
           :prepend t :kill-buffer t)

          ("d" "Dissertating-related templates")
          ("da" "acknowledgments" entry
           (file+olp ,(drmrd/org-file-to-path "dissertating.org") "Refile")
           ,(s-concat "* Acknowledgment for %^{Name to Acknowledge} :Acknowledgments:\n"
                      "%^{Message}\n")
           :prepend t :immediate-finish nil :kill-buffer t)
          ("dc" "citation needed" entry
           (file+olp ,(drmrd/org-file-to-path "dissertating.org") "Refile")
           ,(s-concat "* TODO Citation Needed: [[%l][%^{(Short) Cite Link Name|Here}]] :CITEME:\n"
                      "Created: %u\n%^{Comments|}\n")
           :prepend t :immediate-finish nil :kill-buffer t)
          ("dn" "note" entry
           (file+olp ,(drmrd/org-file-to-path "dissertating.org") "Refile")
           ,(s-concat "* %^{Note Headline} %^g:NOTE:\n"
                      "%^{Description (optional)}\n")
           :prepend t :kill-buffer t)
          ("dq" "quickref" entry
           (file+olp ,(drmrd/org-file-to-path "dissertating.org") "QuickRefs")
           ,(s-concat "** %^{Result Description}\n"
                      ":PROPERTIES:\n"
                      ":Citation: %^{BibTeX Key}\n"
                      ":Result: %^{Result}\n"
                      ":END:")
           :kill-buffer t)
          ("dt" "task" entry
           (file+olp ,(drmrd/org-file-to-path "dissertating.org") "Refile")
           ,(s-concat "* TODO [[%l][Link]] %^{Task Headline} %^g\n"
                      "%^{Description (optional)}\n")
           :prepend t :kill-buffer t)

          ("t" "General task and note templates")
          ("tm" "maybe" entry
           (file ,(drmrd/org-file-to-path "refile.org"))
           "* MAYBE [[%l][Link]] %^{Task Headline} %^g\n%^{Description (optional)}\n"
           :prepend t :kill-buffer t)
          ("tt" "todo" entry
           (file ,(drmrd/org-file-to-path "refile.org"))
           "* TODO [[%l][Link]] %^{Task Headline} %^g\n%^{Description (optional)}\n"
           :prepend t :kill-buffer t)

          ("n" "Learn something new? Jot it down here!")
          ("nn" "anything and everything" entry
           (file ,(drmrd/org-file-to-path "refile.org"))
           "* %u %^{Note Headline} %^g:NOTE:\n%^{Description (optional)}\n"
           :prepend t :immediate-finish nil :kill-buffer t)

          ("e" "event" entry
           (file+olp ,(drmrd/org-file-to-path "calendar.org") "Default")
           "* %^{Brief description} %^g\nSCHEDULED: %t\n%i\n%a")

          ("H" "habit" entry
           (file+olp ,(drmrd/org-file-to-path "habits.org") "Default")
           "** TODO %^{Brief habit description} %^g\nSCHEDULED: %(format-time-string \"%<<%Y-%m-%d %a .+1d/3d>>\")\n:PROPERTIES:\n:STYLE: habit\n:END:")

          ("h" "heart" table-line
           (file+olp ,(drmrd/org-file-to-path "health.org") "Blood Pressure & Heart Rate")
           "| %T | %^{Systolic (Upper #)} | %^{Diastolic (Lower #)} | %^{Pulse (beats / min)} | %^{Comments} |"
           :immediate-finish t :kill-buffer t)

          ("b" "org protocol default capture" entry
           (file+datetree ,(drmrd/org-file-to-path "notes.org"))
           "* %^{Title}\n\n  Source: %u, %c\n\n  %i"
           :empty-lines 1)
          ))
#+END_SRC
** Remove empty logbook entries when capturing                     :Logbook:
Now we add code to remove logbook entries that are created but empty,
which occur when we spend less than a minute capturing something.

#+BEGIN_SRC emacs-lisp
  ;; Remove empty LOGBOOK drawers on clock out
  (defun bh/remove-empty-drawer-on-clock-out ()
    (interactive)
    (save-excursion
      (beginning-of-line 0)
      (org-remove-empty-drawer-at (point))))

  (add-hook 'org-clock-out-hook 'bh/remove-empty-drawer-on-clock-out 'append)
#+END_SRC
* Org Protocol
#+SRC_NAME configure_org-protocol
#+BEGIN_SRC emacs-lisp
  (setq-default org-protocol-default-template-key "b")
  (require 'org-protocol)
#+END_SRC

#+BEGIN_EXAMPLE emacs-lisp
  (setq-default org-capture-templates
        '(("b" "Default template"
           entry
           (file+headline "~/org/capture.org" "Notes")
           "* %^{Title}\n\n  Source: %u, %c\n\n  %i"
           :empty-lines 1)
          ;; ... more templates here ...
          ))
  ;; `b' makes this one the default template used for "org-protocol://capture://"
  ;;     URLs (configurable via the `org-protocol-default-template-key' variable
  ;; `entry' makes it a regular entry with a headline
  ;; `file+headline' files the note in file "~/org/capture.org" as child of the
  ;;                 headline "Notes"
  ;; `%c' will be replaced by an Org-link pointing to the location of the page you
  ;;      have been visiting when clicking on the link. The page title will be the
  ;;      link's description.
  ;; `%i' will be replaced by the selected text in your browser window if any.
#+END_EXAMPLE
* Org Refile
** Setting up refile targets
By default, org-refile only supports refiling trees in the current
buffer to beneath other top level headers in the same buffer. We can
change this by configuring [[help:org-refile-targets][org-refile-targets]] appropriately.
#+SRC_NAME custom_org-refile-targets_setup
#+BEGIN_SRC emacs-lisp
    (setq-default org-refile-targets
          '((org-agenda-files . (:maxlevel . 1))))
#+END_SRC
* Org Habit                                                          :Habits:
#+SRC_NAME setup_org-habit
#+BEGIN_SRC emacs-lisp
  (require 'org-habit)
#+END_SRC
* (Org) HabitRPG
#+SRC_NAME habitrpg_use-package
#+BEGIN_SRC emacs-lisp :tangle no
; (unless (boundp 'spacemacs-version) "yes")
  (use-github-package habitrpg "ryjm/habitrpg.el"
    :config
    (progn (load-file (concat (expand-file-name drmrd/secrets-directory "habitrpg.el")))

           (setq-default hrpg-repeat-interval 900)
           (add-hook 'org-clock-in-hook 'habitrpg-clock-in)
           (add-hook 'org-clock-out-hook 'habitrpg-clock-out)

           (add-to-list 'hrpg-bad-tags-list '("wasting_time" . "10 minutes")))
    :bind (("<f9> a" . habitrpg-status)
           ("C-c C-x h" . habitrpg-add)))
#+END_SRC
* Org Pomodoro                       :org_pomodoro:GTD:TaskMgmt:Productivity:
#+SRC_NAME org-pomodoro_use-package
#+BEGIN_SRC emacs-lisp :tangle no
; (unless (boundp 'spacemacs-version) "yes")
  (use-package org-pomodoro)
#+END_SRC
* M-Return Settings
** Add setting to separate headings other than tasks by newlines (not enabled by default)
The following serves as a simple example of how to tweak M-Return's
behavior to contextually insert lines between headings. It replaces
the usual =org-meta-return= function bound to M-Return with
=smart-org-meta-return-dwim=, which sets =org-blank-before-new-entry=
to =nil= contextually.
#+BEGIN_SRC emacs-lisp :tangle no
  (setq-default org-blank-before-new-entry
        '((heading . always)
          (plain-list-item . nil)))

  (defun call-rebinding-org-blank-behaviour (fn)
    (let ((org-blank-before-new-entry
           (copy-tree org-blank-before-new-entry)))
      (when (org-at-heading-p)
        (rplacd (assoc 'heading org-blank-before-new-entry) nil))
      (call-interactively fn)))

  (defun smart-org-meta-return-dwim ()
    (interactive)
    (call-rebinding-org-blank-behaviour 'org-meta-return))

  ;;; TODO: Is this function ever needed?
  (defun smart-org-insert-todo-heading-dwim ()
    (interactive)
    (call-rebinding-org-blank-behaviour 'org-insert-todo-heading))

  (define-key org-mode-map (kbd "M-<return>")
    'smart-org-meta-return-dwim)
#+END_SRC
** Determine when M-Return may split lines
I've lost track of the number of times I've hit M-[Return] in the
middle of a headline intending to create a new headline at the same
level beneath the current one, only to then split the current headline
in two at the cursor's location and form two headlines instead. The
following built-in variable allows this behavior to be tweaked in
different contexts. For contexts in which the variable is =nil=, the
cursor will move to the end of the line before creating a new one. It
might take some tweaking to figure out in which of these contexts I
want which behavior, but here's a start.
#+BEGIN_SRC emacs-lisp
    ;;; Determine when M-Return can split lines
    (setq-default org-M-RET-may-split-line
      '((default  . t)
        (headline . nil)
        (item     . nil)
        (table    . t)))
#+END_SRC
* Prevent Editing of Invisible Regions
#+BEGIN_SRC emacs-lisp
  ;; Have org try to prevent editing of invisible regions (e.g., folded
  ;; sections). Refer to the variable's docstring for all of its
  ;; possible settings (there are five in total).
  (setq-default org-catch-invisible-edits 'smart)
#+END_SRC
* Org Babel: Set Default Header Arguments
** Set default header arguments
The global defaults for how code-blocks are evaluated in org-mode are
stored in *=org-babel-default-header-args=*. Change the default
setting for code-block evaluation, so that the results of evaluation
are not displayed in a new element.
#+BEGIN_SRC emacs-lisp
  (setq-default org-babel-default-header-args
    (cons '(:results . "silent")
          (assq-delete-all :results org-babel-default-header-args)))
#+END_SRC
** Load extra languages
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'org
    ; (setq geiser-default-implementation 'mit)
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((scheme . t)
       (python . t))))
#+END_SRC
* Ensure that syntax highlighting is enabled while in Org Mode
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'turn-on-font-lock) ; not needed when `global-font-lock-mode' is on
#+END_SRC
* Org Src (Code Blocks)
** Syntax Highlighting
The following uses "native fontification" to enable syntax highlighting in code
blocks.
#+BEGIN_SRC emacs-lisp
  (setq org-src-fontify-natively t)
#+END_SRC
** Tab Behavior
Next we make sure =[TAB]= behaves the way we'd expect inside code blocks,
indenting the code in a way that's appropriate for each block's language.
#+BEGIN_SRC emacs-lisp
  (setq org-src-tab-acts-natively t)
#+END_SRC
** Avoid Flycheck's checkdoc warnings
#+SRC_NAME org-src_disable_flycheck_checkdoc
#+BEGIN_SRC emacs-lisp
  (defun disable-flycheck-in-org-src-block ()
    (setq-local flycheck-disabled-checkers '(emacs-lisp-checkdoc)))

  (add-hook 'org-src-mode-hook 'disable-flycheck-in-org-src-block)
#+END_SRC
* Load Minor Modes
** Auto Fill Mode
=auto-fill-mode= works beautifully in Org files, and we enable it
accordingly.
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'auto-fill-mode)
#+END_SRC
* Keybindings

#+BEGIN_SRC emacs-lisp
  ;;; Access the Org Agenda with "C-c a"
  ;;;
  ;;;     From the Agenda, you can view all todos and other things in org that
  ;;;     have looming deadlines.
  (global-set-key "\C-ca" 'org-agenda)

  ;;; Store an org-link to the current location in org-stored-links
  ;;; with "C-c l"
  ;;;
  ;;;     The same link can be inserted elsewhere later from the
  ;;;     org-stored-links variable using "C-c C-l"
  (global-set-key "\C-cl" 'org-store-link)

  ;;; Switch to another org buffer with "C-c b"
  ;;;
  ;;;     Switches to the org buffer with a given name.
  ; (global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC

* Create Custom Easy Templates
[[http://orgmode.org/manual/Easy-Templates.html][Easy Templates]] serve as a simple way to enter code blocks, quotes,
examples, LaTeX code, etc. in Org files without having to type out an
entire block start or end tag. Better still, we can create our own!
(See the code below for inspiration.)

#+BEGIN_SRC emacs-lisp [:results output silent]
  ;;; Creates an "el" Easy Template in Org Mode.
  ;;;
  ;;;     Typing "<el" followed by [TAB] replaces <el with
  ;;;
  ;;;         #+BEGIN_SRC emacs-lisp
  ;;;           [Cursor Here]
  ;;;         #+END_SRC
  (add-to-list 'org-structure-template-alist
       '("el" "#+SRC_NAME ?\n#+BEGIN_SRC emacs-lisp\n\n#+END_SRC" ""))
#+END_SRC
* Org-Latex Configuration
#+BEGIN_EXAMPLE
  (require 'ox-latex)
  (add-to-list 'org-latex-classes
               '("beamer"
                 "\\documentclass\[presentation\]\{beamer\}"
                 ("\\section\{%s\}" . "\\section*\{%s\}")
                 ("\\subsection\{%s\}" . "\\subsection*\{%s\}")
                 ("\\subsubsection\{%s\}" . "\\subsubsection*\{%s\}")))
#+END_EXAMPLE
* Org Ref
#+SRC_NAME org-ref_use-package
#+BEGIN_SRC emacs-lisp
  (use-package org-ref :ensure t
    :init (setq org-ref-default-bibliography reftex-default-bibliography
                bibtex-completion-bibliography reftex-default-bibliography))
#+END_SRC
